# We need to setup different context root for the auth server so that we can store separate
# cookies for both the API gateway as well as the OAuth2 authorization server.
server:
  port: 8899
  contextPath: /userauth
  servlet-path: /oauth/**,/login,/me

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  user:
    password: password
  basic:
    enabled: true

# Datasource and JPA configuration to be used for storing the OAuth authorization details
# and token store
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  thymeleaf:
    prefix: /templates/
    suffix: .html
    cache: false
logging:
  level:
     org:
       springframework: DEBUG
